### PR TITLE
tagu310model

### PR DESCRIPTION
**Pull request by lakshmichoppillil**
### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet#device-model-repository-client) CLI.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### CODE REVIEW

**Comment by rido-min** [comment]
@lakshmichoppillil the model you submitted defines custom semantic types, like the `did` in the example below.

```json
{
  "@type": [
	"Telemetry", "did"
  ],
  "name": "did",
  "displayName": "did",
  "description": "Device ID tagging.",
  "schema": "string"
}
```

Can you clarify the purpose of these custom semantic types?

**Comment by lakshmichoppillil** [comment]
> @lakshmichoppillil the model you submitted defines custom semantic types, like the `did` in the example below.
> 
> ```json
> {
>   "@type": [
> 	"Telemetry", "did"
>   ],
>   "name": "did",
>   "displayName": "did",
>   "description": "Device ID tagging.",
>   "schema": "string"
> }
> ```
> 
> Can you clarify the purpose of these custom semantic types?

Hello sir,

Because we have used did and cid in our telemetry data for the identification purpose.

did is used as device id for device identification and cid is used as application identifier from our TagU.

Hope this answers your doubts.

Please feel free to ping for any more queries.

**Comment by rido-min** [comment]
@lakshmichoppillil  telemetry data sent by the device will not include the `identifier`.  There is a potential issue by using the "semantic type" for this. 

Wondering if you could identify based on the `name` or `displayName`, so instead of 
```
{
  "@type": [
	"Telemetry", "did"
  ],
  "name": "did",
  "displayName": "did",
  "description": "Device ID tagging.",
  "schema": "string"
}
```

change it to 

```
{
  "@type":  "Telemetry", 
  "name": "did",
  "displayName": "did",
  "description": "Device ID tagging.",
  "schema": "string"
}
```

For `did` and all other telemetries.

**Comment by BerryTsai** [comment]
HI lakshmichoppillil, I am Berry Tsai from Microsoft Taiwan that responsibility technical support APAC for IoT Plug and Play.
If possible, Could you send me mail that I can provide more detail IoT Plug and Play technical information and support for you?
My mail  betsai@microsoft.com

**Review by rido-min — APPROVED** [review]

**Comment by lakshmichoppillil** [comment]
Hello sir,

There are some series of events that happened between these periods of time since I replied to you. The model  has been modified as per the feedback from Ricardo Minguez(Github ). Then the final published model is seen in https://github.com/Azure/iot-plugandplay-models/tree/main/dtmi/ust, the model file is attached here (see published model zip  attachment ).

This model was verified in azure central and the screenshot of that verification is also added here

[cid:76086306-80d3-4325-ad71-d8c5fe4f9174]

But when this published model is used in https://certify.azure.com/   to do the tests for validation in the portal, I got the errors are below for the telemetry .

[cid:90c0df49-c140-4e6d-9fb3-dba675ff63c3]
while the property details are also showing error as below :
[cid:79eb03bc-2eae-477a-871f-cdd141745abf]


Then now I changed the  TagU model again as per  suggestion from Berrytsai of Microsoft Taiwan (Berry Tsai <betsai@microsoft.com<mailto:betsai@microsoft.com>>).Can you please check the model JSON files I edited according to your suggestions?(Please see attached model modified zip folder)

Please find the result below sent from RPi to the azure central using the new model.




[cid:d78aeac0-6130-4ef5-8b80-6142954045c6]

But there are some concerns in this data :
1.The pressure, accelerometer, beacons, GPS, and steps, it is categorized as the unmodeled data.

2.Will this unmodelled data cause any issues in the next steps?

3.Is it possible to combine all the interfaces in a single JSON file?

4.Is it possible to push more than one JSON file to the repository?.

Please try to look at the  model and let me know any doubts you have in any points I state above,


Lakshmi Choppillil
UST Global (Singapore) Pte Limited
300 Beach Road #11-05/06 The Concourse
Singapore 199555
[cid:a982b58b-c45f-44a5-a4ff-89ca6b45cfb7]

________________________________

**Comment by rido-min** [comment]
Hi  @lakshmichoppillil ,

Unfortunately the screenshots/attachments are not available, so I'm not sure if I follow your issue.

I tried the model `dtmi:ust:tagu310;1` in Central and seems to work as expected, note that the RawData view might require some time (minutes) to recognize the telemetry being sent.

To answer your questions.
1. Can you share your Central app to see the unmodeled data issue?
2. If the device template/model is recognized the data should be "modeled"
3. Yes,  you can add all your interfaces in a single file by placing them in an Array
4. Yes, you can add multiple interfaces, with dependencies to the same repository

/c @BerryTsai

**Comment by lakshmichoppillil** [comment]
Hello sir,

I understood that you were able to test the modified model in azure central. But I think you are using simulated device so that you dont have any unmodeled data.But our payload is having sensor values too, we were using the payload with sensor values like accelerometer and pressure values .Thats why we have unmodelled data.

I am attaching all the screenshots in the zip folder, which you mentioned you were not able to see in the last email.

I am pasting my last email here again with the images in zip folder.

[
There are some series of events that happened between these periods of time since I replied to you. The model  has been modified as per the feedback from Ricardo Minguez(Github ). Then the final published model is seen in https://github.com/Azure/iot-plugandplay-models/tree/main/dtmi/ust, the model file is attached here (see published model zip  attachment ).

This model was verified in azure central and the screenshot of that verification is also added here. (see the image1 in zip folder)

But when this published model is used in https://certify.azure.com/   to do the tests for validation in the portal, I got the errors are below for the telemetry. (see the image2 in zip folder )

while the property details are also showing error as below : (see the image3 in zip folder)

Then now I changed the  TagU model again as per  suggestion from Berrytsai of Microsoft Taiwan (Berry Tsai <betsai@microsoft.com<mailto:betsai@microsoft.com>>).Can you please check the model JSON files I edited according to your suggestions?(Please see attached model modified zip folder)

Please find the result below sent from RPi to the azure central using the new model.

( see the image4 in zip folder)


]



Can I clear one doubt about the azure central validation you did with the model? Did you use " import as a model" or "import as interface" using the modified  model in azure central?

Can you provide your email address so that we can add you in the azure central app and pass you the access?

Thanks, and regards
Lakshmi Choppillil
UST Global (Singapore) Pte Limited
300 Beach Road #11-05/06 The Concourse
Singapore 199555
[cid:4b6062be-c8ba-491b-97b2-e3ca57fc4f4d]


Lakshmi Choppillil
UST Global (Singapore) Pte Limited
300 Beach Road #11-05/06 The Concourse
Singapore 199555
[cid:07334426-7b45-4a4d-8f83-b8133f11a43d]


________________________________

**Comment by lakshmichoppillil** [comment]
Hello sir,

I dont really able to model because of some conventions difference I think.

Can you help me on this ?

**Comment by rido-min** [comment]
Happy to help, you can contact me via email: rmpablos at microsoft dot com.

**Pull request merged**
