### PR TITLE
Addition of device models for Eurotech Reliagate 10-12-6x.

### PR DESCRIPTION
**Pull request by dwoodard1**
Signed-off-by: David Woodard <david.woodard@eurotech.com>

### Company Info
Eurotech
https://www.eurotech.com/en

### IoT Plug and Play Device Info

ReliaGate 10-12-6x
https://www.eurotech.com/en/products/iot/multi-service-iot-edge-gateways/reliagate-10-12

### Model Submission Goals
Plug and Play certification for the device
Presence in the Certified Device catalog

### CODE REVIEW

**Comment by rido-min** [comment]
Hi @dwoodard1, 

Thanks for submitting DTDL models to this repo. Before accepting the PR, can you update it to make sure it's up to date with the base branch?

**Comment by dwoodard1** [comment]
Hello @rido-min 

Sorry about that, can you check now?

**Comment by rido-min** [comment]
I merged #118 and it made this PR to be out-of-date with the base branch again. Can you update it again? (sorry about that).

I'd suggest to create future PRs with the setting `Allow edits from maintainers` as described [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by dwoodard1** [comment]
@rido-min It is updated again.

**Review by rido-min — APPROVED** [review]

**Pull request merged**
