### PR TITLE
Create EIC-1000 

### PR DESCRIPTION
**Pull request by VecowChrisHuang**
### Thank you for contributing to the IoT Plug and Play Models repository

:memo: Please review this checklist before submission

- [x] :eyes: The models submitted in this PR follow the [DTDL Naming Guidelines](https://github.com/Azure/iot-plugandplay-models-tools/wiki/DTDL-Naming-Guidelines) for contributing to this repository.
- [x] 🕵️I have validated the models locally using the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.
- [x] ❗ I understand once the PR is approved, the models are considered immutable: any edits will require to submit new files.
- [x] ✨ When creating a new top level `dtmi:namespace`, I have completed the [PR Info Template](#pr-info-template) below.

:zap: PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).

## PR Info Template

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve the _IoT Plug and Play_ ecosystem.

👇: Please replace the markdown comment examples with your own values.

### Company Info

> Info identifying your company (if applicable).

### Model Submission Goals

> Info related to broader submission goals.  

### Code Owners & Reserved Names

> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

### CODE REVIEW

**Review by rido-min — CHANGES_REQUESTED** [review]
Seems the file name does not follow the rule, it should be `-2.json` to match the root `@id` version.

I'd like to ask approval to @chrishuang19790528 as he was the first user submitting interfaces for the root namespace `vecow`.

We have recenly updated the PR template, I'd appreciate it if you could update it.

**Comment by VecowChrisHuang** [comment]
update new json for eic-1000

**Comment by rido-min** [comment]
Can you get the approval from @chrishuang19790528 ? as he was the first user submitting interfaces for the root namespace vecow.

We have recenly updated the PR template, I'd appreciate it if you could update it.

**Review by VecowChrisHuang — COMMENTED** [review]
reupload this eic_1000-1.json file

**Comment by rido-min** [comment]
Hi @VecowChrisHuang

Can ask @chrishuang19790528 to confirm?

**Comment by chrishuang19790528** [comment]
I confirmed it. but how to  approve it?

**Review by rido-min — APPROVED** [review]

**Pull request merged**
