### PR TITLE
add command function

### PR DESCRIPTION
**Pull request by 0hotpotman0**
### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### Company Info
seeed studio

### IoT Plug and Play Device Info
Wio terminal

### Model Submission Goals
add water switch command function 

### Code Owners & Reserved Names
N/a

### CODE REVIEW

**Comment by rido-min** [comment]
hi @0hotpotman0  can you resolve the conflicts?

**Comment by 0hotpotman0** [comment]
> hi @0hotpotman0 can you resolve the conflicts?



> hi @0hotpotman0 can you resolve the conflicts?

Hi rido  
I changed the command order and resubmit it, it was probably the last time I did the wrong commit action.

**Comment by rido-min** [comment]
there are two issues here.
- This repo does not allow any changes, only additions. 
- There is merge conflict in your commit

I'd suggest the next steps:

1. Close this PR
2. Update your fork (Fetch upstream)
3. Add the new file, eg: `dtmi:tinkergen:wioterminal_garden;2`
4. Submit a new PR

**Comment by 0hotpotman0** [comment]
> there are two issues here.
> 
> * This repo does not allow any changes, only additions.
> * There is merge conflict in your commit
> 
> I'd suggest the next steps:
> 
> 1. Close this PR
> 2. Update your fork (Fetch upstream)
> 3. Add the new file, eg: `dtmi:tinkergen:wioterminal_garden;2`
> 4. Submit a new PR

np        thank you rido

**Pull request closed without merging**
