### PR TITLE
roll back to last version for resolve the conflict 

### PR DESCRIPTION
**Pull request by 0hotpotman0**
### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### Company Info
SeeedStudio

### IoT Plug and Play Device Info
Wio Terminal

### Model Submission Goals
roll back to last version for resolve the conflict 

### Code Owners & Reserved Names
N/a

### CODE REVIEW

**Comment by rido-min** [comment]
Hi @0hotpotman0 

Seems this PR cannot trigger the validation checks. 

Do you mind closing this and start a brand new PR?

Thanks !!

**Comment by digimaun** [comment]
> Hi @0hotpotman0
> 
> Seems this PR cannot trigger the validation checks.
> 
> Do you mind closing this and start a brand new PR?
> 
> Thanks !!

One thing to try is PR'ing from a branch in your fork that is not `main`.

**Comment by 0hotpotman0** [comment]
Hi rido, digimaun
The last time I pull request, but there was got a problem, and  I check my log, there has an extra commit, so I try to roll back to the last version, then merge to here, I have closed and reopen it twice yesterday, but still the same situation, please give some help, many thanks.   

Best regards 
fenyi

**Comment by digimaun** [comment]
> Hi rido, digimaun The last time I pull request, but there was got a problem, and I check my log, there has an extra commit, so I try to roll back to the last version, then merge to here, I have closed and reopen it twice yesterday, but still the same situation, please give some help, many thanks.
> 
> Best regards fenyi

Hey Fenyi,

A problem with this PR (and your last PR #411 ) is the set of changes in the commit history causing the latest snapshot to produce 0 Files changed 
image

Instead of using a base commit from Sept 4th

image

We'd recommend updating your fork PR branch state to refresh to the latest changes from this repo

image

Then applying your DTDL/PnP model content on top of that newer state and PR'ing those changes (with the updated commit history).

**Comment by rido-min** [comment]
Hi @0hotpotman0

This PR still cannot trigger the validation checks.

Do you mind closing start a new one?

Thanks !!

**Comment by rido-min** [comment]
Hi @0hotpotman0

Is there anything we can do to help with this PR? I'd suggest to close it and create a new one based on a new branch/fork.

**Comment by rido-min** [comment]
Hi @0hotpotman0

I'm closing this PR, let us know if you need help submitting a new one.

**Pull request closed without merging**
