### PR TITLE
Edit EGW-5200

### PR DESCRIPTION
**Pull request by ADLINK-EPM**
### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### CODE REVIEW

**Review by rido-min — CHANGES_REQUESTED** [review]
@ADLINK-EPM 

Please resolve the conflicts

**Comment by ADLINK-EPM** [comment]
I have made my changes, please help to check if it is correct

**Comment by rido-min** [comment]
seems you have modified a file that was already committed. You should add a new file instead.

**Comment by ADLINK-EPM** [comment]
So I have to create new EGW_5200-2 ?
My purpose is to change the content of the original egw_5200-1

**Comment by rido-min** [comment]
exactly, this repository requires modifications to be made in new versions.

**Comment by ADLINK-EPM** [comment]
I do not know what you mean
So I created egw_5200-2 correct?

**Comment by ADLINK-EPM** [comment]
I have created a new egw_5200-2
Please help to confirm that the action is correct

**Pull request closed without merging**
