### PR TITLE
Commit more Nexcom Popular Gateway device.

### PR DESCRIPTION
**Pull request by allanchen1971**
Add Nexcom popular gateway device : (appc3154/ippc2150p/neu-x100/neu-x300/nife105w/nife200p2e/nife300e3/nise107/nise108/nise3600p2e/nise3800p2e/nise3900p2e/nise4200/nise4300/smb210) to public repository

### CODE REVIEW

**Review by rido-min — COMMENTED** [review]
Hi @llanchen1971, I see the Xcares1 interface several times in this PR. 

These interfaces are meant to describe device interactions. If two or more devices use the same interface there is no need to create one interface per device. 

It's ok to have different devices implementing the same interface.

Because once approved these models become immutable, I'd like to double check with you before accepting.

Thanks,
Rido

**Comment by allanchen1971** [comment]
Dear Sir,
Follow your suggestions, I had changed to using component and verify the
model can work.
I re-sent the PR again, please check it again.

Allan.

Ricardo Minguez (Rido) <notifications@github.com> 於 2020年10月21日 週三
上午12:33寫道：

**Comment by rido-min** [comment]
Thanks for the update @allanchen1971,

As you can see in the [PR checks](https://github.com/Azure/iot-plugandplay-models/runs/1285710056?check_suite_focus=true#step:5:22), there is an error with the filename casing:

`ERROR: in current path /home/runner/work/iot-plugandplay-models/iot-plugandplay-models/dtmi/nexcom/nexdeviceInfo-1.json, expecting /home/runner/work/iot-plugandplay-models/iot-plugandplay-models/dtmi/nexcom/nexdeviceinfo-1.json.`

Can you update this PR?

Thanks,
Rido

PS: Just a reminder that different products can use the same interface. There is no need to submit one interface per device.

**Comment by allanchen1971** [comment]
Dear Sir,
Yes, I had update it.

Ricardo Minguez (Rido) <notifications@github.com> 於 2020年10月21日 週三
下午10:45寫道：

**Review by rido-min — APPROVED** [review]
LGTM

**Pull request merged**
