### PR TITLE
Create puzzlein005-1.json

### PR DESCRIPTION
**Pull request by timtsai0224**
### Company Info

- IEI
- [Company website](https://www.ieiworld.com/_index/tw/)

### IoT Plug and Play Device Info

- PUZZLE-IN005
- TANK-880-Q370
- PUZZLE-IN003B
- DRPC-130-AL
- PUZZLE-IN002
- PUZZLE-IN004
- PUZZLE-IN001A

### Model Submission Goals

- Device certification

### CODE REVIEW

**Review by timtsai0224 — COMMENTED** [review]
validate-repository-submission

**Review by timtsai0224 — COMMENTED** [review]
validate-repository-submission

**Comment by timtsai0224** [comment]
validate-repository-submission

**Comment by digimaun** [comment]
> validate-repository-submission

Sorry for the confusion, the first time you PR to this repo, a project maintainer has to explicitly allow the validation workflow to execute.

**Review by rido-min — APPROVED** [review]
LGTM

**Comment by timtsai0224** [comment]
> > validate-repository-submission
> 
> Sorry for the confusion, the first time you PR to this repo, a project maintainer has to explicitly allow the validation workflow to execute.

First time using GitHub and Azure those things, sorry for the mistake and thank you for your reminder and reply, thanks

**Pull request merged**
