### PR TITLE
Create thermostat-3.json

### PR DESCRIPTION
**Pull request by radulea62**
Thermostat station for 3 rooms

### Thank you for contributing to the IoT Plug and Play Models repository

:memo: Please review this checklist before submission

- [x] :eyes: The models submitted in this PR follow the [DTDL Naming Guidelines](https://github.com/Azure/iot-plugandplay-models-tools/wiki/DTDL-Naming-Guidelines) for contributing to this repository.
- [x] 🕵️I have validated the models locally using the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.
- [x] ❗ I understand once the PR is approved, the models are considered immutable: any edits will require to submit new files.
- [ ] ✨ When creating a new top level `dtmi:namespace`, I have completed the [PR Info Template](#pr-info-template) below.

:zap: PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).

## PR Info Template

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve the _IoT Plug and Play_ ecosystem.

👇: Please replace the markdown comment examples with your own values.

### Company Info

> Info identifying your company (if applicable).

### Model Submission Goals

> Info related to broader submission goals.  

### Code Owners & Reserved Names

> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

### CODE REVIEW

**Review by rido-min — CHANGES_REQUESTED** [review]
Hi @radulea62 

I'd like to understand what the motivation behind this PR. is. 

It could use components, as the companion `TemperatureController` to manage multiple thermostats. 

Also, we are using the models under `com:example` to show how to implement devices using the Azure IoT SDKs. 

What are your plans to implement this interface?

**Comment by rido-min** [comment]
If you are developing your IoT Device, you should use a namespace that reflects your company, project or device. 
`com:example` is being used for samples showing how to use the Azure IoT devices SDKs for all languages.

This repo is intended to share models for finalized devices, if you are still in testing you should use your own fork (I can provide some tips and tricks on how to use your own private repo)

Still curious to understand why not using the existing Thermostat or TemperatureController

**Comment by radulea62** [comment]
if you can give us some tips and tricks on how to use our own private repo it would be helpful. In this phase of the project development, we wanted to start from a simple model that we can easily modify and test certain functions of our project, but I agree with you that it is better to use a private repo. I will close this PR after giving me tips and tricks.
Thank's

**Comment by rido-min** [comment]
Fork this repo, as you did to create this PR, and use the `raw` github URLs to get to any file in any branch or tag, for eg: the Thermostsat3 is available here https://raw.githubusercontent.com/radulea62/iot-plugandplay-models/thermostat-3/dtmi/com/example/thermostat-3.json

you can also use these _raw_ URLs to configure IoTExplorer, or initialize the ModelRepoClient.

If you need further details, feel free to reach out to: rmpablos at microsoft dot com

**Pull request closed without merging**
