### PR TITLE
Add and delete Pixsee model 

### PR DESCRIPTION
**Pull request by lymantseng**
Company Info
Compal electronics, inc.
https://www.compal.com/

IoT Plug and Play Device Info
Pixsee
https://www.pixseecare.com/en/

Model Submission Goals
Device certification
Presence in the Certified Device catalog

Code Owners & Reserved Names

### CODE REVIEW

**Comment by rido-min** [comment]
Hi @lymantseng,

I see you are having some issues  with this PR. We do not allow any edits on already approved interfaces, if you need to make any change you must update the version. Let me know if you need any help.

**Comment by lymantseng** [comment]
Hi @rido-min 
I already used dmr-client validate these files ,but not find any error.

Could you tell me why can't pass the checks?

**Comment by rido-min** [comment]
> Hi @rido-min
> I already used dmr-client validate these files ,but not find any error.
> 
> Could you tell me why can't pass the checks?

There are two kind errors in the checks:
1. ` reject-model-deletions`  and `reject-model-edits`:  You should not edit or change existing files.
2.  `validate-dtdl-models` is using `dmr-client` you should see the exact same errors locally. @digimaun  can you take a look?

**Comment by lymantseng** [comment]
@rido-min 
Thanks for your reply.
reject-model-deletions and reject-model-edits: You should not edit or change existing files.
is It mean can't edit and change existing files? If need the change the content  ,how can I do ?

**Comment by digimaun** [comment]
> @rido-min
> Thanks for your reply.
> reject-model-deletions and reject-model-edits: You should not edit or change existing files.
> is It mean can't edit and change existing files? If need the change the content ,how can I do ?

@lymantseng if you need to change the content of a particular model that has already been merged into the Models Repository then what you should do is increment the version of the target model and apply your changes in the incremented version and PR that.

**Comment by digimaun** [comment]
@lymantseng I cloned your fork to see if I could reproduce the issue. The model causing the problem from your PR is `dtmi/compal/pixsee/babycam-1.json`  right now it is not well formatted json. And when I run `dmr-client validate` against that model I get:

image

But do keep in mind that models merged to the models repository are immutable. This is to prevent an entity taking a dependency on your model from breaking changes.

If you wanted to change for example the existing merged model like `dtmi:compal:pixsee:environmentSettings;1`. You would create a new file as a sibling called `environmentsettings-2.json` set the dtmi as `dtmi:compal:pixsee:environmentSettings;2` then make the changes and PR this.

**Comment by lymantseng** [comment]
@digimaun 
Thanks , I already fix the json format problem .
 But do keep in mind that models merged to the models repository are immutable. This is to prevent an entity taking a dependency on your model from breaking changes.

If you wanted to change for example the existing merged model like dtmi:compal:pixsee:environmentSettings;1. You would create a new file as a sibling called environmentsettings-2.json set the dtmi as dtmi:compal:pixsee:environmentSettings;2 then make the changes and PR this.  ------Do you mean just can re-name and re-upload?

**Pull request closed without merging**
