### PR TITLE
creat dell_edge_gateway_5200

### PR DESCRIPTION
**Pull request by ADLINK-EPM**
### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### CODE REVIEW

**Comment by ADLINK-EPM** [comment]
messageImage_1647826192410
messageImage_1647826220447
What is the problem that makes this unsuccessful

messageImage_1647829524890
Sorry!
I accidentally clicked on this
Please help to repair

**Comment by rido-min** [comment]
Hi @ADLINK-EPM 

This PR still contains edits to existing interfaces.

I'd suggest to close this PR, and start a new one with the new interfaces you want to publish

**Comment by digimaun** [comment]
> ... What is the problem that makes this unsuccessful

@ADLINK-EPM, in the future you are able to use the [file view](https://github.com/Azure/iot-plugandplay-models/pull/440/files) for the PR to see the submission issues more clearly

image

Or the action summary view
https://github.com/Azure/iot-plugandplay-models/actions/runs/2015028646

image

**Comment by ADLINK-EPM** [comment]
Hi All:
I see what's the problem
But I don't know the rules very well
I don't know where it was renamed
Can you elaborate on where to rename
or help me circle the areas that don't follow the rules

**Comment by ADLINK-EPM** [comment]
HI @rido-min 
I have recovered deleted files
please help me review
thank you

**Review by rido-min — APPROVED** [review]

**Pull request merged**
