### PR TITLE
Obsolete models deleted

### PR DESCRIPTION
**Pull request by Marcel-Ball**
### Thank you for contributing to the Azure IoT Plug and Play Models repository

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

The repository pipeline will ensure minimum validation of incoming DTDL models.  

- PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).
- The same validation can be run locally via the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.

## Requested info template for model(s) submission

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve Plug and Play.

:star2: Please replace the markdown comment examples with your own values.

### CODE REVIEW

**Comment by Marcel-Ball** [comment]
HI,
I would like to delete these two obsolete models from the repository.  Is this possible?  If so, how is it done?

Regards,

Marcel

**Comment by Marcel-Ball** [comment]
> Hi @Marcel-Ball
> 
> This repository does not allow deletions or edits. Once a PR is accepted, we consider all the published interfaces as immutable. See https://github.com/Azure/iot-plugandplay-models/blob/main/pr-reqs.md#deletions-and-edits
> 
> Can you close this PR?

Hi @rido-min,

The two models that I need to delete were published in error and contain information LAB3 would like to keep confidential.  NEXUS is our first product and has not been sold yet so no downstream products have a dependency on these models.  The link you provided says deletion is discouraged, not impossible. Is there any way these two models can be deleted?

Regards,

Marcel

**Comment by rido-min** [comment]
Hi @Marcel-Ball 

Even if we accept this PR to delete those models, those will be kept in the Git history. 

Once the PR is made, those are public and no longer confidential. 

I'd suggest closing this PR

Thanks,
Rido

**Comment by Marcel-Ball** [comment]
> 

Hi Rido,

I understand the models will be kept in the Git history.  If deleted the models will not be visible unless somebody goes looking.  I would like the models deleted.

Regards,

Marcel

**Comment by digimaun** [comment]
@Marcel-Ball , are you good with https://github.com/Azure/iot-plugandplay-models/blob/main/dtmi/lab3/nexus-3.json?

**Comment by Marcel-Ball** [comment]
> @Marcel-Ball , are you good with https://github.com/Azure/iot-plugandplay-models/blob/main/dtmi/lab3/nexus-3.json?

nexus-3.json is good.

**Review by digimaun — APPROVED** [review]

**Pull request merged**
