### PR TITLE
Add device model HD08T30MMC

### PR DESCRIPTION
**Pull request by htweijing**
### Thank you for contributing to the IoT Plug and Play Models repository

:memo: Please review this checklist before submission

- [x] :eyes: The models submitted in this PR follow the [DTDL Naming Guidelines](https://github.com/Azure/iot-plugandplay-models-tools/wiki/DTDL-Naming-Guidelines) for contributing to this repository.
- [x] 🕵️I have validated the models locally using the [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine) command line tool.
- [x] ❗ I understand once the PR is approved, the models are considered immutable: any edits will require to submit new files.
- [x] ✨ When creating a new top level `dtmi:namespace`, I have completed the [PR Info Template](#pr-info-template) below.

:zap: PR validation steps are described in the tools [Wiki](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Validation-Pipeline#pr-validation-checks).

## PR Info Template

When submitting models to the repository we ask that you provide as much of the following meta information around your models and related devices as possible. This info will be used to improve the _IoT Plug and Play_ ecosystem.

👇: Please replace the markdown comment examples with your own values.

### Company Info

- Company name: Hatteland Technology AS
- Company website: www.hattelandtechnology.com

### IoT Plug and Play Device Info

- Product website: https://www.hattelandtechnology.com/view_product?id=280!main_category=Marine%20&%20Offshore=
- OS & Arch: Windows IoT Enterprise

### Model Submission Goals

Device certification: Trusted platform module

### Code Owners & Reserved Names

> Indicates GitHub alias entries to be added to the repo `CODEOWNERS` for the incoming model namespace. The codeowner is expected to be involved in subsequent DTDL model submissions against the same namespace.

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

### CODE REVIEW

**Comment by htweijing** [comment]
@microsoft-github-policy-service agree company="Hatteland Technology AS"

**Review by rido-min — COMMENTED** [review]
any reason to publish a copy of LinuxDeviceInfo instead of reusing the existing one?
https://github.com/Azure/iot-plugandplay-models/blob/main/dtmi/synnex/linuxdeviceinfo-1.json 

same for windowsdeviceinfo

**Comment by htweijing** [comment]
We are create them as placeholder for extending with own customized DMI table properties in future.
Several displayNames will be re-phrased.

Kind Regards

Wei Jing
Senior Design Engineer - Computer
Hatteland Technology AS

Direct Phone
: +47-47686702

**Comment by rido-min** [comment]
Keep in mind this repo does not allow edits on accepted models, so these cannot be used as a placeholder. I'd suggest to make the edits to the descriptions and DMI table in this PR.

**Comment by htweijing** [comment]
I have update the linuxdeviceinfo-1.json and windowsdeviceinfo-1.json with customized fields.

**Review by rido-min — APPROVED** [review]

**Comment by htweijing** [comment]
A followup question: 
When can this model be populated in https://devicemodels.azure.com ?
Checked yesterday, it seems to be not listed there.

**Comment by rido-min** [comment]
thanks for pointing this out !! we had an issue in the publishing pipeline, the model is available now in https://devicemodels.azure.com/dtmi/hattelandtechnology/hd08t30mmc-1.json

**Pull request merged**
